### ISSUE TITLE
Deleting files according to constraints

### ISSUE THREAD

**Issue by jaekwon** [tendermint/go-autofile#1]
When the max group size has been reached, the Group should delete them.  Optionally, we can let move them somewhere.

Having a GroupReader still reading a file, should probably prevent that file from being deleted.  This means writing may block until a GroupReader progresses.

**Comment by zramsay** [comment]
Issue moved to [tendermint/tmlibs #43](https://github.com/tendermint/tmlibs/issues/43) via [**ZenHub**](https://www.zenhub.com/)
